export const images = [
    {
        src: `https://source.unsplash.com/2ShvY8Lf6l0/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/Dm-qxdynoEc/800x799`,
        width: 1,
        height: 1,
        title: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been`,
    },
    {
        src: `https://source.unsplash.com/qDkso9nvCg0/600x799`,
        width: 3,
        height: 4,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/iecJiKe_RNg/600x799`,
        width: 3,
        height: 4,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/epcsn8Ed8kY/600x799`,
        width: 3,
        height: 4,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/NQSWvyVRIJk/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/zh7GEuORbUw/600x799`,
        width: 3,
        height: 4,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/PpOHJezOalU/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/I1ASdgphUH4/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/XiDA78wAZVw/600x799`,
        width: 3,
        height: 4,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/x8xJpClTvR0/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/qGQNmBE7mYw/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/NuO6iTBkHxE/800x599`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/pF1ug8ysTtY/600x400`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://source.unsplash.com/A-fubu9QJxE/800x533`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
    {
        src: `https://images.unsplash.com/photo-1545586867-a0dd5984124c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1471&q=80`,
        width: 4,
        height: 3,
        title: `Gabriel rega é cigano`,
    },
];
